### ISSUE TITLE
No E-mail export option; make use of the share sheet?

### ISSUE THREAD

**Issue by koenraijer** [rob-miller/rTracker-swift#2]
![WhatsApp Image 2024-03-05 at 09 11 29](https://github.com/rob-miller/rTracker-swift/assets/75178793/db43a744-0598-4675-9597-c4185572c407)

It would perhaps be quite accessible to make use of the share sheet, like they're doing here: https://stackoverflow.com/questions/35851118/how-do-i-share-files-using-share-sheet-in-ios? 

(I have no swift experience, otherwise I'd have a go at it myself...)

**Comment by rob-miller** [comment]
The email options appear according to the result of `MFMailComposeViewController.canSendMail()` which returns "true if the device is configured for sending email or false if it is not."  In my experience this most likely means you don't have an email account configured in your Settings.

However yes, the system share sheet is a much better solution now, and I've been meaning to implement it.  Thanks for the link!

**Comment by rob-miller** [comment]
Closed by #4
